### ISSUE TITLE
Build fails on Freebsd 12.1

### ISSUE THREAD

**Issue by m1357** [zeek/bro-netmap#11]
System : 12.1-RELEASE-p6 FreeBSD 12.1-RELEASE-p6 GENERIC  amd64
version: zeek-3.2.1

FreeBSD clang version 8.0.1 (tags/RELEASE_801/final 366581) (based on LLVM 8.0.1)
Target: x86_64-unknown-freebsd12.1
Thread model: posix
InstalledDir: /usr/bin

configure output:
./configure
Build Directory        : build
Zeek Source Directory  : 
-- The C compiler identification is Clang 8.0.1
-- The CXX compiler identification is Clang 8.0.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test cxx17_already_works
-- Performing Test cxx17_already_works - Failed
-- Performing Test cxx17_works
-- Performing Test cxx17_works - Success
-- Found BinPAC: /opt/app/zeek/bin/binpac  
-- Found CAF: 0.17.6  found components: core io openssl 
-- Found Broker: /opt/app/zeek/lib/libbroker.so  
-- Zeek executable      : /opt/app/zeek/bin/zeek
-- Zeek source          : 
-- Zeek build           : 
-- Zeek install prefix  : /opt/app/zeek
-- Zeek plugin directory: /opt/app/zeek/lib/zeek/plugins
-- Zeek debug mode      : 
-- Found Netmap: /usr/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /root/bro-netmap/build

cd to build and make:

 make
Scanning dependencies of target bro-plugin-Zeek_Netmap
[ 20%] Creating __bro_plugin__ for Zeek::Netmap
[ 20%] Built target bro-plugin-Zeek_Netmap
Scanning dependencies of target copy-scripts-Zeek_Netmap
[ 20%] Built target copy-scripts-Zeek_Netmap
Scanning dependencies of target generate_outputs
[ 20%] Built target generate_outputs
Scanning dependencies of target Zeek-Netmap.freebsd-amd64
[ 40%] Building CXX object CMakeFiles/Zeek-Netmap.freebsd-amd64.dir/src/Plugin.cc.o
In file included from /root/bro-netmap/src/Plugin.cc:2:
/root/bro-netmap/src/Plugin.h:10:33: warning: 'Plugin' is deprecated: Remove in v4.1. Use zeek::plugin::Plugin instead [-Wdeprecated-declarations]
class Plugin : public ::plugin::Plugin
                                ^
/root/zeek-3.2.1/src/plugin/Plugin.h:906:16: note: 'Plugin' has been explicitly marked deprecated here
using Plugin [[deprecated("Remove in v4.1. Use zeek::plugin::Plugin instead")]] = zeek::plugin::Plugin;
               ^
In file included from /root/bro-netmap/src/Plugin.cc:2:
/root/bro-netmap/src/Plugin.h:14:18: warning: 'Configuration' is deprecated: Remove in v4.1. Use zeek::plugin::Configuration instead [-Wdeprecated-declarations]
        virtual plugin::Configuration Configure();
                        ^
/root/zeek-3.2.1/src/plugin/Plugin.h:902:23: note: 'Configuration' has been explicitly marked deprecated here
using Configuration [[deprecated("Remove in v4.1. Use zeek::plugin::Configuration instead")]] = zeek::plugin::Configuration;
                      ^
In file included from /root/bro-netmap/src/Plugin.cc:3:
In file included from /root/bro-netmap/src/Netmap.h:9:
In file included from /usr/include/net/netmap_user.h:104:
In file included from /usr/include/net/netmap.h:816:
/usr/include/stdatomic.h:186:17: error: unknown type name '_Bool'
typedef _Atomic(_Bool)                  atomic_bool;
                ^
/usr/include/stdatomic.h:186:26: error: C++ requires a type specifier for all declarations
typedef _Atomic(_Bool)                  atomic_bool;
~~~~~~~                                 ^
/usr/include/stdatomic.h:379:17: error: unknown type name '_Bool'
static __inline _Bool
                ^
/usr/include/stdatomic.h:383:10: error: address argument to atomic operation must be a pointer to _Atomic type ('volatile atomic_bool *' (aka 'volatile int *') invalid)
        return (atomic_exchange_explicit(&__object->__flag, 1, __order));
                ^                        ~~~~~~~~~~~~~~~~~
/usr/include/stdatomic.h:242:2: note: expanded from macro 'atomic_exchange_explicit'
        __c11_atomic_exchange(object, desired, order)
        ^                     ~~~~~~
/usr/include/stdatomic.h:390:2: error: address argument to atomic operation must be a pointer to _Atomic type ('volatile atomic_bool *' (aka 'volatile int *') invalid)
        atomic_store_explicit(&__object->__flag, 0, __order);
        ^                     ~~~~~~~~~~~~~~~~~
/usr/include/stdatomic.h:256:2: note: expanded from macro 'atomic_store_explicit'
        __c11_atomic_store(object, desired, order)
        ^                  ~~~~~~
/usr/include/stdatomic.h:394:17: error: unknown type name '_Bool'
static __inline _Bool
                ^
/root/bro-netmap/src/Plugin.cc:10:9: warning: 'Configuration' is deprecated: Remove in v4.1. Use zeek::plugin::Configuration instead [-Wdeprecated-declarations]
plugin::Configuration Plugin::Configure()
        ^
/root/zeek-3.2.1/src/plugin/Plugin.h:902:23: note: 'Configuration' has been explicitly marked deprecated here
using Configuration [[deprecated("Remove in v4.1. Use zeek::plugin::Configuration instead")]] = zeek::plugin::Configuration;
                      ^
/root/bro-netmap/src/Plugin.cc:15:10: warning: 'Configuration' is deprecated: Remove in v4.1. Use zeek::plugin::Configuration instead [-Wdeprecated-declarations]
        plugin::Configuration config;
                ^
/root/zeek-3.2.1/src/plugin/Plugin.h:902:23: note: 'Configuration' has been explicitly marked deprecated here
using Configuration [[deprecated("Remove in v4.1. Use zeek::plugin::Configuration instead")]] = zeek::plugin::Configuration;
                      ^
4 warnings and 6 errors generated.
*** Error code 1

Stop.
make[2]: stopped in /root/bro-netmap/build
*** Error code 1

Stop.
make[1]: stopped in /root/bro-netmap/build
*** Error code 1

Stop.
make: stopped in /root/bro-netmap/build

**Comment by awelzel** [comment]
Hey @m1357 , thanks for the report. My current understanding is that this happens because `netmap.h` on FreeBSD has an unconditional `#include <stdatomic.h>` and that doesn't work when compiling with C++. I'm planning to report it to the netmap project.

Maybe, if you're up for it, the following patch should work around the issue, but it isn't great. Maybe someone here has a better idea how to go about this.

```
diff --git a/src/Netmap.h b/src/Netmap.h
index ca799ce..90004c1 100644
--- a/src/Netmap.h
+++ b/src/Netmap.h
@@ -3,6 +3,20 @@
 #ifndef IOSOURCE_PKTSRC_NETMAP_SOURCE_H
 #define IOSOURCE_PKTSRC_NETMAP_SOURCE_H
 
+//
+// FreeBSD netmap.h has an unconditional #include <stdatomic.h> which
+// can't be used with C++. Include what's needed from <atomic> here
+// and define _STDATOMIC_H_ so #include <stdatomic.h> is short-circuited.
+//
+// :-(
+//
+#if defined(__FreeBSD__)
+#include <atomic>
+using std::memory_order_release;
+using std::memory_order_acquire;
+#define _STDATOMIC_H_
+#endif
+
 extern "C" {
 #include <pcap.h>
 #define NETMAP_WITH_LIBS
```

**Comment by m1357** [comment]
I'm a little confused on this. Should the patch be applied to the bro-netmap src Netmap.h or the /usr/src/sys/net/netmap.h ?
I applied to the bro-netmap/src/Netmap.h and it succeeded:
patch -C < ../netmaph.patch 
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/src/Netmap.h b/src/Netmap.h
|index ca799ce..90004c1 100644
|--- a/src/Netmap.h
|+++ b/src/Netmap.h
--------------------------
Patching file Netmap.h using Plan A...
Hunk #1 succeeded at 3.
done

But build still failed. 


When I try to apply to the /usr/src/sys/net/netmap.h (I altered the file name in the patch to match the capitalization :

patch -C < /root/bro-netmap/netmaph.patch
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/src/netmap.h b/src/netmap.h
|index ca799ce..90004c1 100644
|--- a/src/netmap.h
|+++ b/src/netmap.h
--------------------------
Patching file netmap.h using Plan A...
Hunk #1 failed at 3.
1 out of 1 hunks failed while patching netmap.h
done

This is the first 50 lines from the freebsd source tree of netmap.h:

cat netmap.h.orig | head -50
/*-
 * SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * Copyright (C) 2011-2014 Matteo Landi, Luigi Rizzo. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *   1. Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``S IS''AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*
 * $FreeBSD: releng/12.1/sys/net/netmap.h 352355 2019-09-15 14:26:19Z vmaffione $
 *
 * Definitions of constants and the structures used by the netmap
 * framework, for the part visible to both kernel and userspace.
 * Detailed info on netmap is available with "man netmap" or at
 *
 *	http://info.iet.unipi.it/~luigi/netmap/
 *
 * This API is also used to communicate with the VALE software switch
 */

#ifndef _NET_NETMAP_H_
#define _NET_NETMAP_H_

#define	NETMAP_API	14		/* current API version */

#define	NETMAP_MIN_API	14		/* min and max versions accepted */
#define	NETMAP_MAX_API	15


Thanks for your help and patience.

**Comment by awelzel** [comment]
> I'm a little confused on this. Should the patch be applied to the bro-netmap src Netmap.h or the /usr/src/sys/net/netmap.h ?

`bro-netmap/src/Netmap.h`

> I applied to the bro-netmap/src/Netmap.h and it succeeded:
> patch -C < ../netmaph.patch
> Hmm... Looks like a unified diff to me...
> The text leading up to this was:

This looks almost good, but please remove `-C`.  This is equivalent to `--check` and `--dry-run` so it will not do any modifications. The following should work:
```
$ patch  < ../netmaph.patch
```

You can thereafter inspect `src/Netmap.h` to see if it contains the changes.

Thanks for testing!

**Comment by m1357** [comment]
ah yes, my bad :). Build and install succeeds with the patch. Here is the output:
Scanning dependencies of target bro-plugin-Zeek_Netmap
[ 20%] Creating __bro_plugin__ for Zeek::Netmap
[ 20%] Built target bro-plugin-Zeek_Netmap
Scanning dependencies of target copy-scripts-Zeek_Netmap
[ 20%] Built target copy-scripts-Zeek_Netmap
Scanning dependencies of target generate_outputs
[ 20%] Built target generate_outputs
Scanning dependencies of target Zeek-Netmap.freebsd-amd64
[ 40%] Building CXX object CMakeFiles/Zeek-Netmap.freebsd-amd64.dir/src/Plugin.cc.o
In file included from /root/bro-netmap/src/Plugin.cc:2:
/root/bro-netmap/src/Plugin.h:10:33: warning: 'Plugin' is deprecated: Remove in v4.1. Use zeek::plugin::Plugin instead [-Wdeprecated-declarations]
class Plugin : public ::plugin::Plugin
                                ^
/opt/app/zeek/include/zeek/plugin/Plugin.h:906:16: note: 'Plugin' has been explicitly marked deprecated here
using Plugin [[deprecated("Remove in v4.1. Use zeek::plugin::Plugin instead")]] = zeek::plugin::Plugin;
               ^
In file included from /root/bro-netmap/src/Plugin.cc:2:
/root/bro-netmap/src/Plugin.h:14:18: warning: 'Configuration' is deprecated: Remove in v4.1. Use zeek::plugin::Configuration instead [-Wdeprecated-declarations]
        virtual plugin::Configuration Configure();
                        ^
/opt/app/zeek/include/zeek/plugin/Plugin.h:902:23: note: 'Configuration' has been explicitly marked deprecated here
using Configuration [[deprecated("Remove in v4.1. Use zeek::plugin::Configuration instead")]] = zeek::plugin::Configuration;
                      ^
/root/bro-netmap/src/Plugin.cc:10:9: warning: 'Configuration' is deprecated: Remove in v4.1. Use zeek::plugin::Configuration instead [-Wdeprecated-declarations]
plugin::Configuration Plugin::Configure()
        ^
/opt/app/zeek/include/zeek/plugin/Plugin.h:902:23: note: 'Configuration' has been explicitly marked deprecated here
using Configuration [[deprecated("Remove in v4.1. Use zeek::plugin::Configuration instead")]] = zeek::plugin::Configuration;
                      ^
/root/bro-netmap/src/Plugin.cc:15:10: warning: 'Configuration' is deprecated: Remove in v4.1. Use zeek::plugin::Configuration instead [-Wdeprecated-declarations]
        plugin::Configuration config;
                ^
/opt/app/zeek/include/zeek/plugin/Plugin.h:902:23: note: 'Configuration' has been explicitly marked deprecated here
using Configuration [[deprecated("Remove in v4.1. Use zeek::plugin::Configuration instead")]] = zeek::plugin::Configuration;
                      ^
4 warnings generated.
[ 60%] Building CXX object CMakeFiles/Zeek-Netmap.freebsd-amd64.dir/src/Netmap.cc.o
[ 80%] Linking CXX shared module lib/Zeek-Netmap.freebsd-amd64.so
[ 80%] Built target Zeek-Netmap.freebsd-amd64
Scanning dependencies of target dist
[100%] Building binary plugin package: Zeek_Netmap.tar.gz
[100%] Built target dist


I'll update once I get a bit further in the setup if this is functional or not. Thank you again for the help.

**Comment by shirkdog** [comment]
This also builds for me on FreeBSD 13-CURRENT as well. Now to test if it is working correctly.

**Comment by sethhall** [comment]
I *finally* integrated @shirkdog's changes.  So I think this ticket is closable.
