### ISSUE TITLE
Netmap/lb crash once plugin attaches

### ISSUE THREAD

**Issue by m1357** [zeek/bro-netmap#4]
using intel x520 on freebsd 11.3 p1 and p2. Tested zeek 2.6.2 and 2.6.3. plugin built from source and zkg  lb starts and runs fine using : lb -i ix2 -p20 -o 20. as soon as bro is started packets are no longer forwarded. Restarting lb results in 0 packets incoming to netmap. 

Dmesg after bro startup:
042.301729 [1766] netmap_ring_reinit        called for ix2 RX5 042.304510 [1721] nm_rxsync_prologue        ix2 RX11: fail 'head < kring->nr_hwcur || head > kring->nr_hwtail' h 302 c 302 t 304 rh 302 rc 302 rt 304 hc 304 ht 304 042.304533 [1766] netmap_ring_reinit        called for ix2 RX11 042.304558 [1766] netmap_ring_reinit        called for ix2 RX15 042.307984 [1766] netmap_ring_reinit        called for ix2 RX6 042.308521 [1766] netmap_ring_reinit        called for ix2 RX7 042.313627 [1766] netmap_ring_reinit        called for ix2 RX6 042.314349 [1766] netmap_ring_reinit        called for ix2 RX1 042.317253 [1723] nm_rxsync_prologue        ix2 RX5: fail 'cur < head || cur > kring->nr_hwtail' h 273 c 272 t 273 rh 273 rc 272 rt 273 hc 272 ht 273 042.319884 [1726] nm_rxsync_prologue        ix2 RX4: fail 'head < kring->nr_hwcur && head > kring->nr_hwtail' h 4094 c 4094 t 2 rh 4094 rc 4094 rt 2 hc 4095 ht 2 042.321352 [1723] nm_rxsync_prologue        ix2 RX10: fail 'cur < head || cur > kring->nr_hwtail' h 432 c 431 t 432 rh 432 rc 431 rt 432 hc 431 ht 432 042.321993 [1723] nm_rxsync_prologue        ix2 RX1: fail 'cur < head || cur > kring->nr_hwtail' h 3751 c 3750 t 3751 rh 3751 rc 3750 rt 3751 hc 3750 ht 3751 042.360195 [1723] nm_rxsync_prologue        ix2 RX2: fail 'cur < head || cur > kring->nr_hwtail' h 2678 c 2677 t 2678 rh 2678 rc 2677 rt 2678 hc 2677 ht 2678 042.380046 [1723] nm_rxsync_prologue        ix2 RX6: fail 'cur < head || cur > kring->nr_hwtail' h 3787 c 3786 t 3787 rh 3787 rc 3786 rt 3787 hc 3786 ht 3787

**Comment by sethhall** [comment]
I'm not sure there is enough information to go on here.  Please file this ticket again if it's still relevant.
