### ISSUE TITLE
Netmap plugin for freebsd 12.1, will be release?

### ISSUE THREAD

**Issue by vinceplayer** [zeek/bro-netmap#7]
Hi the plugin bro-netmap is only compatibile with FreeBSD 11.
 Are there any development plans, to bring it to freebsd 12?

thank you very much

**Comment by 0xxon** [comment]
Hi,

I don't think any of the developers is currently running FreeBSD 12 - and this plugin is developed under what I would call a "best effort" scheme.

That being said - we are happy for patches to make this work under FreeBSD 12.

**Comment by sethhall** [comment]
I think the new release works now.
