### ISSUE TITLE
Is this plugin still under maintained?

### ISSUE THREAD

**Issue by WqyJh** [zeek/bro-netmap#8]
Does bro-netmap have been deprecated or need contributors?
Is there any alternatives for zeek/netmap integration?

**Comment by 0xxon** [comment]
This will take a bit of a longer answer.

No, it is not deprecated. That being said - the developers of Zeek only use this in already existing very specific environments. Thus we don't really become quickly aware of problems. In addition to this - netmap support is not one of our core features - so it gets more of a "best effort" support. This can sometimes take a while; we are often a bit too busy for our own good.

We are always happy about contributions.

There is no alternative for zeek/netmap integration that I know of.

**Comment by WqyJh** [comment]
I'm working on porting bro-netmap to zeek. Currently, I was able to compile/test/install/run on zeek environment. Should I contribute it back to this project?

Personally speaking, I think there should be another project called `zeek/zeek-netmap` to support zeek, and remain this repository to support bro.

Following is the running processes, shows that there's workers running on netmap.
```bash
 8994 pts/3    S+     0:00 sudo lb -i enp0s9 -p zeek:2
 8995 pts/3    Sl+    0:19 lb -i enp0s9 -p zeek:2
21480 ?        S      0:00 /bin/bash /usr/local/zeek/share/zeekctl/scripts/run-zeek -1 -U .status -p zeekctl -p zeekctl-live -p local -p manager local.zeek zeekctl base/frameworks/cluster zeekctl/auto
21486 ?        Sl     0:00 /usr/local/zeek/bin/zeek -U .status -p zeekctl -p zeekctl-live -p local -p manager local.zeek zeekctl base/frameworks/cluster zeekctl/auto
21528 ?        S      0:00 /bin/bash /usr/local/zeek/share/zeekctl/scripts/run-zeek -1 -U .status -p zeekctl -p zeekctl-live -p local -p proxy-1 local.zeek zeekctl base/frameworks/cluster zeekctl/auto
21534 ?        Sl     0:00 /usr/local/zeek/bin/zeek -U .status -p zeekctl -p zeekctl-live -p local -p proxy-1 local.zeek zeekctl base/frameworks/cluster zeekctl/auto
21582 ?        S      0:00 /bin/bash /usr/local/zeek/share/zeekctl/scripts/run-zeek 0 -i netmap::zeek}0 -U .status -p zeekctl -p zeekctl-live -p local -p worker-1-1 local.zeek zeekctl base/frameworks/cluster zeekctl/auto
21585 ?        S      0:00 /bin/bash /usr/local/zeek/share/zeekctl/scripts/run-zeek 1 -i netmap::zeek}1 -U .status -p zeekctl -p zeekctl-live -p local -p worker-1-2 local.zeek zeekctl base/frameworks/cluster zeekctl/auto
21597 ?        Sl     0:00 /usr/local/zeek/bin/zeek -i netmap::zeek}1 -U .status -p zeekctl -p zeekctl-live -p local -p worker-1-2 local.zeek zeekctl base/frameworks/cluster zeekctl/auto
21598 ?        Sl     0:00 /usr/local/zeek/bin/zeek -i netmap::zeek}0 -U .status -p zeekctl -p zeekctl-live -p local -p worker-1-1 local.zeek zeekctl base/frameworks/cluster zeekctl/auto
21720 pts/4    S+     0:00 grep --color=auto zeek
```

Here is my working repository https://github.com/WqyJh/zeek-netmap.

**Comment by sethhall** [comment]
I'm going to close this ticket now that this repo is updated and I can't easily see what changes you made to it in your repo because you didn't fork the repo.  If you have any fixes that you'd like to get into (the now) zeek-netmap repo, feel free to submit a pull request.

Thanks!
